version: '3.2'
services:
  redis:
    image: "redis"
    restart: always
    ports:
    - "6379:6379"
    volumes:
      - type: bind
        source: /home/ubuntu/redis-data
        target: /data
    environment:
    - HELLO=hyman
    command: redis-server --appendonly yes

  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=123456

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
    - "5672:5672"
    - "15672:15672"
